-- ============================================================
-- Makeable Jobs — Seed Data (demo listings)
-- ============================================================

insert into public.companies (name, slug, logo, website, industry, description, location, size, rating, review_count, verified) values
  ('Nova Labs',     'nova-labs',     'https://logo.clearbit.com/novalabs.example',     'https://novalabs.example',     'SaaS',         'Cloud-native SaaS platform for analytics.', 'Bengaluru, India', '51-200', 4.6, 87, true),
  ('VertexAI',      'vertexai',      'https://logo.clearbit.com/vertexai.example',      'https://vertexai.example',      'Artificial Intelligence', 'Applied AI startup building LLM tooling.', 'Remote', '11-50', 4.8, 42, true),
  ('FinEdge',       'finedge',       'https://logo.clearbit.com/finedge.example',       'https://finedge.example',       'Fintech',       'Digital banking for emerging markets.', 'Mumbai, India', '201-500', 4.3, 156, false),
  ('PixelCraft',    'pixelcraft',    'https://logo.clearbit.com/pixelcraft.example',    'https://pixelcraft.example',    'Design & Media','Design studio and creative agency.', 'Gurugram, India', '11-50', 4.4, 63, false),
  ('HealthSync',    'healthsync',    'https://logo.clearbit.com/healthsync.example',    'https://healthsync.example',    'Healthcare',    'Digital health platform connecting patients and providers.', 'Hyderabad, India', '51-200', 4.5, 91, true),
  ('QuantumLabs',   'quantumlabs',   'https://logo.clearbit.com/quantumlabs.example',   'https://quantumlabs.example',   'Deep Tech',     'Hardware-adjacent deep-tech research lab.', 'Pune, India', '501-1000', 4.7, 210, true),
  ('GrowthHub',     'growthhub',     'https://logo.clearbit.com/growthhub.example',     'https://growthhub.example',     'Marketing',     'Growth marketing and SEO platform.', 'Remote', '11-50', 4.2, 38, false)
on conflict (slug) do nothing;

insert into public.jobs (external_id, source, title, description, company_id, company_name, company_logo, location, remote, salary_min, salary_max, salary_currency, salary_text, job_type, level, skills, apply_url, apply_on, experience_min, experience_max, posted_at, expires_at, active, sponsored) values
  ('li-1001', 'linkedin', 'Senior Flutter Developer', 'Build cross-platform mobile apps with Flutter. Ship features end-to-end, mentor juniors and own app architecture.', (select id from public.companies where slug='nova-labs'), 'Nova Labs', 'https://logo.clearbit.com/novalabs.example', 'Bengaluru, India', true, 1800000, 3000000, 'INR', '₹18L – ₹30L/yr', 'full_time', 'senior', '["Flutter","Dart","Firebase","Riverpod","CI/CD"]'::jsonb, 'https://www.linkedin.com/jobs/view/1001', 'LinkedIn', 4, 7, now() - interval '2 days', now() + interval '30 days', true, true),
  ('li-1002', 'linkedin', 'Flutter Developer (2-4 yrs)', 'Join the mobile team building our consumer app. Work on animations, state management and app store releases.', (select id from public.companies where slug='growthhub'), 'GrowthHub', 'https://logo.clearbit.com/growthhub.example', 'Remote', true, 900000, 1600000, 'INR', '₹9L – ₹16L/yr', 'full_time', 'mid', '["Flutter","Dart","GoRouter","REST APIs"]'::jsonb, 'https://www.linkedin.com/jobs/view/1002', 'LinkedIn', 2, 4, now() - interval '5 days', now() + interval '20 days', true, false),
  ('in-2001', 'indeed', 'Full-Stack Engineer (Next.js)', 'Own product features across the stack with Next.js, TypeScript and PostgreSQL.', (select id from public.companies where slug='finedge'), 'FinEdge', 'https://logo.clearbit.com/finedge.example', 'Mumbai, India', false, 1500000, 2400000, 'INR', '₹15L – ₹24L/yr', 'full_time', 'mid', '["Next.js","TypeScript","PostgreSQL","Tailwind"]'::jsonb, 'https://in.indeed.com/viewjob/2001', 'Indeed', 3, 6, now() - interval '1 day', now() + interval '35 days', true, true),
  ('in-2002', 'indeed', 'Backend Engineer — Python/FastAPI', 'Design and scale REST APIs handling millions of requests. Focus on reliability and observability.', (select id from public.companies where slug='healthsync'), 'HealthSync', 'https://logo.clearbit.com/healthsync.example', 'Hyderabad, India', false, 1400000, 2200000, 'INR', '₹14L – ₹22L/yr', 'full_time', 'mid', '["Python","FastAPI","PostgreSQL","Redis","Docker"]'::jsonb, 'https://in.indeed.com/viewjob/2002', 'Indeed', 3, 6, now() - interval '3 days', now() + interval '25 days', true, false),
  ('nk-3001', 'naukri', 'Frontend Developer (React)', 'Build beautiful, accessible interfaces. Collaborate closely with design and backend teams.', (select id from public.companies where slug='pixelcraft'), 'PixelCraft', 'https://logo.clearbit.com/pixelcraft.example', 'Gurugram, India', false, 800000, 1400000, 'INR', '₹8L – ₹14L/yr', 'full_time', 'mid', '["React","TypeScript","CSS","Framer Motion"]'::jsonb, 'https://www.naukri.com/job/3001', 'Naukri', 2, 5, now() - interval '7 days', now() + interval '28 days', true, false),
  ('nk-3002', 'naukri', 'AI/ML Engineer', 'Train and deploy LLM-based products. Own evaluation pipelines and model quality.', (select id from public.companies where slug='vertexai'), 'VertexAI', 'https://logo.clearbit.com/vertexai.example', 'Remote', true, 2000000, 4000000, 'INR', '₹20L – ₹40L/yr', 'full_time', 'senior', '["Python","PyTorch","LLMs","RAG","MLOps"]'::jsonb, 'https://www.naukri.com/job/3002', 'Naukri', 4, 8, now() - interval '10 days', now() + interval '40 days', true, true),
  ('is-4001', 'internshala', 'Software Engineering Intern', '6-month paid internship. Work on real product features with strong mentorship.', (select id from public.companies where slug='nova-labs'), 'Nova Labs', 'https://logo.clearbit.com/novalabs.example', 'Bengaluru, India', false, 20000, 30000, 'INR', '₹20K – ₹30K/mo', 'internship', 'entry', '["Python","SQL","Communication"]'::jsonb, 'https://internshala.com/internship/4001', 'Internshala', 0, 0, now() - interval '4 days', now() + interval '15 days', true, false),
  ('is-4002', 'internshala', 'UI/UX Design Intern', 'Design mobile-first product experiences. Create prototypes, design systems and user flows.', (select id from public.companies where slug='pixelcraft'), 'PixelCraft', 'https://logo.clearbit.com/pixelcraft.example', 'Gurugram, India', false, 15000, 25000, 'INR', '₹15K – ₹25K/mo', 'internship', 'entry', '["Figma","UI Design","Prototyping"]'::jsonb, 'https://internshala.com/internship/4002', 'Internshala', 0, 0, now() - interval '1 day', now() + interval '20 days', true, false),
  ('wf-5001', 'wellfound', 'Founding Mobile Engineer', 'First mobile hire at a seed-stage startup. Own the iOS/Android app from scratch.', (select id from public.companies where slug='vertexai'), 'VertexAI', 'https://logo.clearbit.com/vertexai.example', 'Remote', true, 2500000, 4500000, 'INR', '₹25L – ₹45L/yr + equity', 'full_time', 'lead', '["Flutter","Firebase","Push Notifications","GraphQL"]'::jsonb, 'https://wellfound.com/jobs/5001', 'Wellfound', 5, 9, now() - interval '6 days', now() + interval '30 days', true, true),
  ('co-6001', 'company', 'Staff Software Engineer — Platform', 'Design platform services and shared infrastructure for a deep-tech lab. Impactful, research-leaning role.', (select id from public.companies where slug='quantumlabs'), 'QuantumLabs', 'https://logo.clearbit.com/quantumlabs.example', 'Pune, India', false, 3000000, 5000000, 'INR', '₹30L – ₹50L/yr', 'full_time', 'lead', '["Distributed Systems","Go","Rust","Kubernetes"]'::jsonb, 'https://careers.quantumlabs.example/jobs/staff-platform', 'Company Website', 8, 12, now() - interval '12 days', now() + interval '45 days', true, false);

-- Demo saved job / notification for the demo admin user (created via auth signup)
insert into public.searches (query, filters, result_count) values
  ('Flutter Developer', '{"remote": true}'::jsonb, 3),
  ('Remote Jobs',       '{"remote": true}'::jsonb, 5),
  ('Chennai Jobs',      '{"location": "Chennai"}'::jsonb, 0);