include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: false
    avoid_print: false
    sort_child_properties_last: true

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
